### ISSUE TITLE
Update Conda Env Recipe

### ISSUE THREAD

**Issue by eyoung55** [NREL/WindSE#86]
## Description
The Conda environment recipe is out of date and should be updated to the latest packages. It might also be nice to "relax" some of the dependencies and only pin specific versions where we know it's needed. It should also be possible to add the pip installs to the Conda recipe.

```yaml
name: windse
channels:
  - defaults
dependencies:
  - openmdao=3.9.2
  - pytest=6.2.4
  - scipy=1.7.0
  - mshr=2019.1.0
  - pandas=1.4.0
  - dolfin-adjoint=2019.1.0
  - pyyaml=5.4.1
  - matplotlib=3.4.2
  - fenics=2019.1.0
  - memory_profiler=0.58.0
```
